### PR TITLE
Add more Q/A, fix grammar & typos

### PR DESCRIPTION
**Pull request by Nicklaus-s**
* defraud (illegally obtain money from someone by deception.) -> deceive
* add q/a for flag docs & flag edited list
* community section - grammar fixes

### CODE REVIEW

**Comment by Nicklaus-s** [comment]
I think the `div` alignment might be messed up? Not sure.

Not sure why my commits aren't being signed, but if this can be overridden than I would be thankful 😢

**Comment by Kaiddd** [comment]
Still says the commits aren't signed @Nicklaus-s

**Comment by Coolreindeer** [comment]
Hi @Kaiddd. Just wanted to say great job on this Client Optimizer but I do have a question. When I download this onto Roblox and load up murder mystery 2 most of my weapons wont load in my inventory. is there a setting I can change for it to work? Thanks. Sorry if I wasted your time.

**Comment by Kaiddd** [comment]
> Hi @Kaiddd. Just wanted to say great job on this Client Optimizer but I do have a question. When I download this onto Roblox and load up murder mystery 2 most of my weapons wont load in my inventory. is there a setting I can change for it to work? Thanks. Sorry if I wasted your time.

Please don't reply stuff like this in unrelated issues, make an issue if needed

**Comment by Nicklaus-s** [comment]
Will force commit with signature or close & open a new pull request tomorrow.

**Comment by Kaiddd** [comment]
@Nicklaus-s can you resolve conflicts so I can merge?

**Comment by Kaiddd** [comment]
Another note, we removed the issues page

**Comment by aduud21** [comment]
@Kaiddd sorry if this is off-topic but i think the discord bot in RCO server did not function properly, i asked a staff to agecheck me cause why not then in the channel i said i was 13 and i got instant banned by the bot even though im legit 13 and i got a verified discord bot on discord (im banned on discord.com/invite/CThxh2kyEC)

**Comment by Nicklaus-s** [comment]
will edit & solve conflicts asap

**Comment by Exponential-Workload** [comment]
> Aaaaand that merge is unsigned joy
> 
> Github is so fun x

image
It is signed with Github's UI Key lol

**Comment by Kaiddd** [comment]
The readme has had some changes since this PR, can you make a new PR if you'd still like to submit changes to the new current readme?

**Pull request closed without merging**
